package com.isita.ccapper.app.util;

public class Constantes {
	public static final String PROPIEDADES = "src/main/resources/application.properties";
	public static final String KEY_PRIVATE_TOKEN_RSA="private_key";
	public static final String KEY_PUBLIC_TOKEN_RSA="public_key";
	public static final String APP_CLIENTE="credencial_aplicacion";
	public static final String KEY_CLIENTE_APP="password_aplicacion";
	public static final int EXPIRACION_TOKEN =180;
	public static final String  TIPO_CONSULTA_L1="L1";
	public static final String  TIPO_CONSULTA_L2="L2";
	public static final String  TIPO_CONSULTA_L3="L3";
	public static final String  TIPO_CONSULTA_L4="L4";
	public static final String  TIPO_CONSULTA_C1="C1";
	public static final String VACIO="";
	public static final Integer NUMERO_CERO=0;
	public static final String PERMISO_POST="POST001";
	public static final String PERMISO_GET="GET002";
	public static final String PERMISO_PUT="UPDATE003";
	public static final String PERMISO_DELETE="DELETE004";
	public static final String DELETETYOETWO="E02";
	public static final String TOKEN_EXPIRACION= "tiempo_expiracion_token";
	public static final String REGISTRAR_PRIMER_INTENTO= "registrar_primer_intento";
	public static final int LIMITE_INTENTOS_PARA_LOGUEARSE =3;
	public static final int NUMERO_UNO =1;
	public static final int RANGO_MINUTOS_DE_BLOQUEO=3;
	public static final int RANGO_MINUTOS_PARA_DESBLOQUEAR=3;
	public static final String FECHA_DEFAULT="1900-01-01 00:00:00";
	public static final String SOLO_REGISTRAR_INTENTO="registrar_intento";
	public static final boolean ESTATUS_USUARIO_BLOQUEADO = false;
	public static final String BLOQUEAR_USUARIO="bloquear_usuario";
	public static final String DESBLOQUEAR_USUARIO="desbloquear_usuario";
	public static final int INTENTO_INICIAL_CERO=0;
	public static final int BLOQUEO_POR_INTENTOS = 1;
	public static final String TIPO_CONSULTA_L5="L5";
	public static final Integer REGISTRO_ELIMINADO = 1;
	public static final String TIPO_CONSULTA_L6="L6";
	public static final String URL_TOKEN="/ccapper/app/oauth/token";
	public static final Long NUMERO_CERO_TIPO_LONG=0L;
	public static final String CODIGO_MENSAJE = "00004";
	public static final String DeleteTypeTwo="E02";
	public static final String TIPO_RESPUESTA_SELECCION_UNICO ="radio";
	public static final String TIPO_RESPUESTA_SELECCION_MULTIPLE ="opciones";
}
